stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: your-image-name
  # Adicione outras variáveis de ambiente necessárias

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  only:
    - master

test:
  stage: test
  script:
    - # Comandos para executar testes (incluindo testes de segurança)
  only:
    - master

deploy:
  stage: deploy
  script:
    - # Comandos para implantar a aplicação (por exemplo, usando o Docker)
  only:
    - master
